version: 2
build:
  os: ubuntu-20.04
  image: stable
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
