version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
        - uv sync
    build:
        html:
          - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
    # see https://github.com/readthedocs/readthedocs.org/pull/9649
    post_checkout:
      # Use `git log` to check if the latest commit contains "skip rtd",
      # in that case exit the command with 183 to skip the build
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip rtd") || exit 183

sphinx:
  configuration: docs/source/conf.py

formats: []

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
